### ISSUE TITLE
Function to extract a subset of keys as javascript object on page

### ISSUE THREAD

**Issue by scavpy** [Skyscanner/flask-ptrans#10]
Want a way to put a javascript object containing multiple keys and their translations in the page using a single call.

Needs more design input.

**Comment by inquire** [comment]
So, the goal of this function is to give us a subset of translations from a translation file. We can have either an overloaded function, or define two of them. The two use cases that we want to address are the following. 

1. We have a common substring for the keys for example:

Example:
page_one_heading
page_one_legend

I should be able to say:
    
    ptrans.multikey('en_GB', ['page_one'])

2. We have a common substring or we want to match whole keys as well 

Example:
page_one_heading
page_one_legend
subsection_article

    ptrans.multikey('en_GB', ['page-one', 'subsection_article'])

The output of this should be plain good old json.

**Comment by scavpy** [comment]
Version 0.8.1 has the ptrans_subset() function for this purpose. I'll call this closed.
