### ISSUE TITLE
Psudolocalisation changes placeholders

### ISSUE THREAD

**Issue by divercraig** [Skyscanner/flask-ptrans#15]
If you use ptrans to do psudolocalisation of your strings it will also change the contents of strings within braced brackets { }. This means when you try to use the qps-ploc locale we don't see string replacement because the placeholders are missing.

You also see errors from flask:
ERROR:root:No {ŀȧƀḗŀ} in string shared_form_enter-field, locale qps-ploc

**Comment by scavpy** [comment]
False alarm. Another system was breaking the placeholders.
